require "dotenv/load"
require "httparty"

require_relative "../lib/wettr"
require_relative "../lib/wettr/cli"
require_relative "../lib/wettr/version"
require_relative "../lib/wettr/weather_api"
require_relative "../lib/wettr/ip_api"
require_relative "../lib/wettr/weather"
require_relative "../lib/wettr/ip"